version: '3.7'

services:
  item-app:
    image: item-app:latest # Ganti dengan nama dan versi image item-app yang sesuai
    ports:
      - '80:80'
    depends_on:
      - item-db

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

volumes:
  app-db:
