---
apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: karsajobs
spec:
  type: NodePort
  selector:
    app: karsajobs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30006
